### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by maxidorius** [doofy/mxisd-docker#2]
@doofy FYI, I've now made an official docker image for mxisd, see [here](https://github.com/kamax-io/mxisd/blob/master/Dockerfile).

Differences with yours:
- Much more compact, it's ~110MB when yours is 1GB
- Smaller base image (alpine JDK instead of the big Debian stretch)
- No build in the docker image, compiled binaries are directly added to the container
- `docker stop` works correctly by using a script for the entry point

**Comment by doofy** [comment]
@maxidor thanks for the heads up. I added a note to the readme here that links to your image.
